### ISSUE TITLE
Feature ideas

### ISSUE THREAD

**Issue by bschoepke** [ph1p/figma-blender#1]
I love this add-on and have a couple suggestions:

1. Add ability to export Figma assets at larger resolutions (e.g., 2x)
2. Hook up Transparency by default (just wire the texture node's alpha to the Principal BDSF alpha)

**Comment by ph1p** [comment]
Thanks for your suggestions :) I think both should not be a problem

**Comment by ph1p** [comment]
Released! :) With both of your suggestions! Thank you!

new addon (you can also dowload it from gumroad): [figma-blender-addon.zip](https://github.com/ph1p/figma-blender/files/11420169/figma-blender-addon.zip)
